### PR TITLE
Everything works except for the form, which i would assume works

### PR DESCRIPTION
**Pull request by IanMDonaldson**
see Comment on FILM.JSP can't get the film ATTRIBUTE set, it works
everywhere else in the page EXCEPT for the link. href knocks it out of
scope or something?

### CODE REVIEW

**Comment by RBearSAT** [comment]
Okay, I’ll take a look at it.

 

One thing I’m also going to show you Thursday is how to use regular expressions to validate input. Still working out the details tonight, but it’s something you want to use to make sure input is correct before updating the table.

 

Yea, real development is much more than just a few key routines. It’s a collection of application techniques you use to make the application perform reliable and fast.

 

Randy Bear

Little Rock, AR

**Comment by RBearSAT** [comment]
Got it. Go back and look at WebFilm.java. Look inside the case for “getFilm” and tell me what’s missing. Hint, I think it’s why you’re getting a null pointer exception.

 

Randy Bear

Little Rock, AR

**Comment by RBearSAT** [comment]
Okay, I downloaded your project and am trying to run it. Right now, it’s not returning films so I need to fix that. I’ll look at it tomorrow.

 

Randy Bear

Little Rock, AR

**Comment by IanMDonaldson** [comment]
HURRAH Just committed and pushed to New Branch with a successful update of
film!

**Comment by RBearSAT** [comment]
That’s awesome. Can’t wait to review it. What I REALLY like about your work is that you’re taking what I talk about and extending it even further. That shows me you grasp the concepts and aren’t just parroting back my code. That’s really big when looking at development.

Thursday we’ll look at validates using regular expressions (you’ll see why they are key) and talk about the next steps which I think will be renting a movie.

I also hope I’ll have Docker to a point where we can start to use it to test with. I have two containers talking to each other using Wordpress, but I’m having a problem connecting with the DB container externally.

**Pull request merged**
